# Generated by Django 2.2.6 on 2020-10-02 03:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet_hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_hashtag_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=255)),
                ('tweet_id', models.BigIntegerField(blank=True, default=0)),
                ('tweet_text', models.TextField(blank=True)),
                ('liked_count', models.BigIntegerField(blank=True, default=0)),
                ('retweet_count', models.BigIntegerField(blank=True, default=0)),
                ('hashtag_has', models.IntegerField(blank=True, default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('tweet_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_screen_name', models.CharField(blank=True, max_length=255)),
                ('hashtags', models.CharField(blank=True, max_length=255)),
                ('twitter_id', models.CharField(blank=True, max_length=255)),
                ('twitter_name', models.CharField(blank=True, max_length=255)),
                ('profile_image_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_user_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, default=0)),
                ('followers_count', models.BigIntegerField(blank=True, default=0)),
                ('friends_count', models.BigIntegerField(blank=True, default=0)),
                ('tweet_count', models.BigIntegerField(blank=True, default=0)),
                ('favourites_count', models.BigIntegerField(blank=True, default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_user_timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, default=0)),
                ('tweet_id', models.BigIntegerField(blank=True, default=0)),
                ('tweet_text', models.TextField(blank=True)),
                ('liked_count', models.BigIntegerField(blank=True, default=0)),
                ('retweet_count', models.BigIntegerField(blank=True, default=0)),
                ('tweet_created_date', models.DateTimeField(auto_now_add=True)),
                ('hashtag_array', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.BigIntegerField(default=0)),
                ('s_password', models.CharField(default='', max_length=512)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
